/*
    Version for PostgreSQL
*/
DROP TABLE IF EXISTS FILES;
DROP TABLE IF EXISTS CANDIDATES;


/*
    "Main" table to store data
*/
CREATE TABLE CANDIDATES (
    CANDIDATE_ID SERIAL,
    FIRST_NAME VARCHAR(64) NOT NULL,
    LAST_NAME VARCHAR(64) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    LETTER_ID VARCHAR(64) PRIMARY KEY
);

/*
    Table with files
*/
CREATE TABLE FILES (
    LETTER_ID VARCHAR(64) PRIMARY KEY,
    LETTER_CONTENT BYTEA,
    FOREIGN KEY(LETTER_ID) REFERENCES CANDIDATES(LETTER_ID)
);
